### ISSUE TITLE
Clicking Notifications Menu button changes height.

### ISSUE THREAD

**Issue by beanaroo** [zeroepoch/gnome-shell-extension-shrink-message-tray#2] opened 2015-03-04 02:37 UTC
When I click on the Notifications Menu button in the bottom left corner, the tray's height seems to change back to normal (bleeds off screen). When I close the menu, height returns to expected.

**Comment by zeroepoch** [comment] 2015-03-05 16:26
I'm not able to reproduce this on demand, but I have seen this happen many times.  I'm not sure if there is anything I can do about it.  I believe it's a bug in gnome shell with reloading extensions.  I see a similar thing with dash-to-dock where the size setting sometimes reverts back to the default after dismissing the lock screen.

**Comment by zeroepoch** [comment] 2015-04-08 04:21
I was actually seeing this problem fairly consistently a few weeks ago when I clicked the chat bubble on the left side of the message tray.  Although now that I'm reviewing this issue it's not happening anymore.  Could have been fixed by gnome-shell 3.14.4?  Are you still seeing this problem with the latest 3.14.x gnome-shell?  I doubt my extension works on gnome 3.16 since they made major changes to the message tray.

**Closed as completed by zeroepoch** 2015-04-08 04:21 UTC
